TotalWeight: 100
CatchBlacklist: []
ReleaseBlacklist: [ Ender_Dragon, Wither ]
EntityChance:
  default: 0.1
  animal: 0.75
  monster: 0.25
  villager: 0.75
EntityWeight:
  default: 100
  monster: 100
  animal: 1
  villager: 10
EntityMaxHealth:
  default: 10
  monster: 10
  animal: 100
  villager: 100
DebugMode: false
PokeBallItem:
  Id: 04be8421-c832-4cf8-82e5-9b88d814717e
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDQzZDRiN2FjMjRhMWQ2NTBkZGY3M2JkMTQwZjQ5ZmMxMmQyNzM2ZmMxNGE4ZGMyNWMwZjNmMjlkODVmOGYifX19
  DisplayName: 'Pokéball'
  Category: PokéMob
  Description: 'Catch all your animals or hostile mobs in a portable spawn egg with this Pokéball.'
  Usage: 'Right-click to throw the ball at a mob in order to catch them. If the attempt fails, a particle effect will tell you if it was because of chance, high health, or the pet belongs to somebody else.'